#!/usr/bin/env bash
# cleanup_repo.sh — remove disk bloat & leftover local artifacts.
# Safe to run repeatedly. Does NOT touch git history.
# Run from repo root:  bash scripts/cleanup_repo.sh

set -euo pipefail

if [ ! -d ".git" ]; then
  echo "ERROR: must be run from the repo root (no .git dir found)" >&2
  exit 1
fi

echo "==> Pruning stale git worktrees"
git worktree prune -v || true

echo "==> Removing claude worktree directories"
rm -rf .claude/worktrees

echo "==> Removing duplicate venv/ (keeping .venv/)"
rm -rf venv

echo "==> Removing stray backend/backend/ wrapper directory"
rm -rf backend/backend

echo "==> Removing W&B local logs"
rm -rf backend/wandb

echo "==> Removing evaluation run outputs (regenerated by runner)"
rm -rf evaluation/runs/*/

echo "==> Removing duplicate postcss config (keeping .mjs)"
rm -f frontend/postcss.config.js

echo "==> Removing sandbox probe leftover (if any)"
rm -f test_rm.txt

echo "==> Removing macOS .DS_Store files"
find . -name ".DS_Store" -not -path "./.git/*" -not -path "./.venv/*" -not -path "./node_modules/*" -not -path "./frontend/node_modules/*" -delete 2>/dev/null || true

echo "==> Stale local index.lock (if any)"
rm -f .git/index.lock

echo "==> Pre-commit hook installed?"
if [ -x .git/hooks/pre-commit ]; then
  echo "    yes (.git/hooks/pre-commit exists)"
else
  echo "    no — installing"
  pre-commit install || echo "    install failed; run 'pip install pre-commit && pre-commit install' manually"
fi

echo
echo "Done. Disk usage now:"
du -sh .venv venv backend frontend evaluation 2>/dev/null || true
